#! /usr/bin/python3

import sys
import json
import subprocess
import os

import rbsutils
import cgen

# G L O B A L   V A R I A B L E S
print_column_width = 93
rbs_conf = rbs_cmd = ""
supported_commands = ["clean", "install"]
supported_pkgtypes = ["cmake", "makefile", "boost"]
supported_domains  = ["Linux", "QNX"]


# F U N C T I O N S
def print_domain_separator(domain):
    print("=" * (print_column_width))
    print("Domain Name: %s" % domain)
    print("~" * (13+len(domain)))

    if domain == "QNX":
        rbsutils.print_banner('Configure "qcc -V5.4.0,gcc_ntoarmv7le_gpp -set-default" or similar for your target!')



def get_package_type(pkgd):
    files = subprocess.run(["ls", pkgd], stdout=subprocess.PIPE).stdout.decode('utf-8').split("\n")
    if "Makefile" in files or "makefile" in files:
        return "makefile"
    elif "CMakeLists.txt" in files:
        return "cmake"
    elif "bootstrap.sh" in files and "boost-build.jam" in files:
        return "boost"
    else:
        print("RBS Error: Unknown package type found %s" % (pkgd))
        exit(-1)


def command_check(cmd):
    if cmd in supported_commands:
        return True
    else:
        return False


def domain_folder_paths(domain, pwd, arch):
    outbase, tmp_dir, log_dir = rbsutils.common_folder_paths(pwd)
    out_dir = outbase + "/" + domain + "/" + arch
    bin_dir = out_dir + "/bin/"
    lib_dir = out_dir + "/lib/"
    etc_dir = out_dir + "/etc/"
    return out_dir, bin_dir, lib_dir, etc_dir


def prepare_env_n_dir(conf, domain, env):
    # copy environment settings from toolchain config to target build env
    for v in conf["env"]:
        env[v] = conf["env"][v]

    # get and prepare arch (x86_64, armle-v7 etc) info
    if len(conf["arch"]) == 0:
        print("RBS Error: Target Architecture not configured in toolchain!")
        exit(-1)
    env["ARCH"] = conf["arch"]

    # create out folders and to env variable
    outbase, tmp_dir, log_dir = rbsutils.common_folder_paths(env["PWD"])
    out_dir, bin_dir, lib_dir, etc_dir = domain_folder_paths(domain, env["PWD"], conf["arch"])
    subprocess.run(["mkdir", "-p", out_dir, bin_dir, lib_dir, etc_dir])
    env["OUT_DIR"] = out_dir
    env["BIN_DIR"] = bin_dir
    env["LIB_DIR"] = lib_dir
    env["TMP_DIR"] = tmp_dir
    env["ETC_DIR"] = etc_dir
    env["LOG_DIR"] = log_dir

    # copy target configurations
    target_cfg_bin = env["PWD"] + "/config-target/" + domain + "/bin/*"
    target_cfg_etc = env["PWD"] + "/config-target/" + domain + "/etc/*"
    subprocess.run(["cp -r " + target_cfg_bin + " " + bin_dir], shell=True)
    subprocess.run(["cp -r " + target_cfg_etc + " " + etc_dir], shell=True)

    return env



def get_rbs_module_for_build(pkgt, domain):
    if pkgt not in supported_pkgtypes:
        print("RBS Error: unsupported Package Type \"%s\" identified!" % (pkgt))
        exit(-1)

    if domain not in supported_domains:
        print("RBS Error: unsupported Domain Name \"%s\" passed!" % (domain))
        exit(-1)

    # identify the right module to make future function calls
    rbs_mod = None
    if pkgt == "makefile":
        if domain == "QNX":
            from qnx import makefile as rbs_mod
        elif domain == "Linux":
            from linux import makefile as rbs_mod
    elif pkgt == "boost":
        if domain == "QNX":
            from qnx import boost as rbs_mod
        elif domain == "Linux":
            from linux import boost as rbs_mod
    elif pkgt == "cmake":
        if domain == "QNX":
            from qnx import cmake as rbs_mod
        elif domain == "Linux":
            from linux import cmake as rbs_mod

    return rbs_mod



def build_domain_packages(dconf, domain, pkgs, cmd):
    print("\n")
    print("~" * (18+len(domain)))
    print("RBS begins for %s..." % (domain))
    print("~" * (18+len(domain)))

    # copy host environment and add the envs from json file
    env = os.environ.copy()
    toolch_conf = ""

    # obtain the toolchain json file before env and dir setup
    if len(dconf["toolchain"]["file"]) > 0:
        toolchain_f = env["PWD"] + "/" + dconf["toolchain"]["file"]
        if not os.path.exists(toolchain_f):
            print("RBS Error: Check if toolchain file \"%s\" exists!" % (toolchain_f))
            exit(-1)
        toolch_conf = json.load(open(toolchain_f))
    else:
        print("RBS Error: Toolchain not configured for % domain!" % (domain))
        exit(-1)

    env = prepare_env_n_dir(toolch_conf, domain, env)

    # setup path & domain
    env["DOMAIN"] = domain
    if len(toolch_conf["path"]) > 0:
        env["PATH"] = toolch_conf["path"] + ":" + env["PATH"]

    # build packages for domain (QNX, Linux, ...)
    for pkg in pkgs:
        # identify package type
        print("\nStarting package: " + pkg)
        print("-" * (18+len(pkg)))
        pkgd = dconf["packages"]["path"] + "/" + pkg
        if os.path.exists(pkgd) == False:
            print("Package \"%s\" can't be reached at path \"%s\"! Aborting!" % (pkg, pkgd))
            exit(-1)
        pkgt = get_package_type(pkgd)
        print("Package type: " + pkgt)

        # check fidl scripts and do code generation
        rbs_func = "codegen"
        cconf = {**rbs_conf["code-gen"], **dconf}
        if rbsutils.sstate_check(env, pkg, rbs_func) == False:
            if cgen.cgen_fidl_package(cconf, env, pkg) == True:
                rbsutils.sstate_done(env, pkg, rbs_func)
            else:
                exit(-1)
        else:
            print("Operation[\"%s\"] for package \"%s\" is skipped as it was done already!" % (rbs_func, pkg))


        # get module object to make function calls
        rbs_mod = get_rbs_module_for_build(pkgt, domain)

        # execute build steps...
        if len(cmd) > 0:
            rbs_mod.run_package(dconf, env, pkg, cmd)
        else:
            # patch the package
            rbs_func = "patch"
            # TBD

            # configure package
            rbs_func = "config"
            if rbsutils.sstate_check(env, pkg, rbs_func) == False:
                if rbs_mod.config_package(dconf, env, pkg) == True:
                    rbsutils.sstate_done(env, pkg, rbs_func)
                else:
                    exit(-1)
            else:
                print("Operation[\"%s\"] for package \"%s\" is skipped as it was done already!" % (rbs_func, pkg))

            # compile package
            rbs_func = "compile"
            if rbsutils.sstate_check(env, pkg, rbs_func) == False:
                if rbs_mod.compile_package(dconf, env, pkg) == True:
                    rbsutils.sstate_done(env, pkg, rbs_func)
                else:
                    exit(-1)
            else:
                print("Operation[\"%s\"] for package \"%s\" is skipped as it was done already!" % (rbs_func, pkg))

            # install package
            rbs_func = "install"
            if rbsutils.sstate_check(env, pkg, rbs_func) == False:
                if rbs_mod.install_package(dconf, env, pkg) == True:
                    rbsutils.sstate_done(env, pkg, rbs_func)
                else:
                    exit(-1)
            else:
                print("Operation[\"%s\"] for package \"%s\" is skipped as it was done already!" % (rbs_func, pkg))

    # end of function
    print("\n")



def build_packages(conf, cmd):
    rbsutils.sstate_prebuild_check()
    domain_index = -1
    for domain in conf["domains"]:
        domain_index += 1
        print_domain_separator(domain["name"])

        # identify the packages to be built
        print("\nPackages to be built for %s:" % (domain["name"]))
        packages = []
        for item in domain["packages"]["list"]:
            packages.append(item["pkg"])

        if len(packages) == 0:
            print("No package configured for %s domain, skipping..." % (domain["name"]))
            continue
        else:
            print(packages)

        build_domain_packages(domain, domain["name"], packages, cmd)


if __name__ == '__main__':
    cmd_args = len(sys.argv)
    if cmd_args > 1:
        for i in range(1, cmd_args):
            if sys.argv[i] == "-c" and (i+1) <= cmd_args:
                rbs_cmd = sys.argv[i+1]
                i += 1
                cmdchk = command_check(rbs_cmd);
                if cmdchk == True:
                    continue
                else:
                    print("RBS Error: %s is not supported!" % (rbs_cmd))
                    exit(-1)
    else:
        print("usage:\n"+sys.argv[0]+" <rbs.json file>\n")
        exit(-1)

    # load RBS configuration from JSON file
    print("Loading %s...\n" % (sys.argv[1]))
    rbs_conf = json.load(open(sys.argv[1])) # Load the json file
    print("=" * (print_column_width))
    print("Welcome to RBS - Runtime Build System!")
    rbs_domains = []
    for domain in rbs_conf["domains"]:
        rbs_domains.append(domain["name"])
    print("%s is configured for the domain targets: %s" % (rbs_conf["title"], rbs_domains))

    # build packages for all domains...
    build_packages(rbs_conf, rbs_cmd)
    rbsutils.print_banner("Build succeeded!")
